[package]
name = "asm-repair"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.6.0"
eyre = "0.6.12"
polars = { version = "0.39.2", features = ["lazy", "csv", "concat_str", "strings"] }
