# Each sequence should be renamed to have chr and haplotype information in its label.
# ex. sample_chr1_(h1|h2|haplotype1|haplotype2)ctg
# ex. sample_chr10_(mat|pat)ctg
# All fa should be indexed.
cen_contigs: "data/platinum_genomes/config/cen_ctgs.tsv"
misassemblies: "data/platinum_genomes/config/cen_ctgs_misassemblies.tsv"
assembly_fai: "data/platinum_genomes/config/assembly_fai.tsv"
concensus:
  base_group: "verkko"
  gap_open_penalty: -50
  gap_ext_penalty: 0
